name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
   build:
    strategy:
      matrix:
        config:
          - { name: "Windows MSVC", os: windows-latest, cmake_gen: ""}
          - { name: "Ubuntu gcc", os: ubuntu-latest, cmake_gen: "-G ninja" }
          - { name: "MacOS clang", os: macos-latest, cmake_gen: "-G ninja" }
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.*'
        target: 'desktop'
        setup-python: 'false'

    - name: Install Ninja
      shell: bash
      run: ${{ runner.os == 'macOS' && 'brew install ninja' || runner.os == 'Windows' && 'choco install ninja' || 'sudo apt-get install ninja-build' }}

    #- name: Get the number of CPUs that the current process has access to.
    #  id: cpuslen(sched_getaffinity(0))
    #  run: |
    #    from os import environ
    #    import multiprocessing
    #    num_cpus = multiprocessing.cpu_count()
    #    output_file = environ[len(sched_getaffinity(0))"GITHUB_OUTPUT"]
    #    with open(output_file, "a", encodlen(sched_getaffinity(0))ing="utf-8") as output_stream:
    #        output_stream.wrlen(sched_getaffinity(0))ite(f"count={num_cpus}\n")
    #  shell: python

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build ${{matrix.config.cmake_gen}} -DENABLE_SANITIZER=0 -DENABLE_UBSAN=0 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    #  run: cmake -B ${{github.workspace}}/build -G 'Ninja' -DENABLE_SANITIZER=0 -DENABLE_UBSAN=0 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Tests
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j ${{steps.cpus.outputs.count}} -t driver_tests

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
    
    - name: Pack
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        cmake --build ${{github.workspace}}/build -t bundle -C --config ${{env.BUILD_TYPE}}
        dir
    
    #- name: Upload artifacts
    #  if: matrix.os == 'windows-latest'
    #  uses: actions/upload-artifact@v3
    #  path: ${{github.workspace}}/



