name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
   build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.*'
        target: 'desktop'
        setup-python: 'false'

    #- name: Install Ninja
    #  shell: bash
    #  run: ${{ runner.os == 'macOS' && 'brew install ninja' || runner.os == 'Windows' && 'choco install ninja' || 'sudo apt-get install ninja-build' }}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DENABLE_SANITIZER=0 -DENABLE_UBSAN=0 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    #  run: cmake -B ${{github.workspace}}/build -G 'Ninja' -DENABLE_SANITIZER=0 -DENABLE_UBSAN=0 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Tests
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -t driver_tests

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
    
    - name: Pack
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        cmake --build ${{github.workspace}}/build -t bundle
        dir
    
    #- name: Upload artifacts
    #  if: matrix.os == 'windows-latest'
    #  uses: actions/upload-artifact@v3
    #  path: ${{github.workspace}}/



